numero = int(input('Digite um número inteiro: '))
n = str(numero)
print(f'Analisando o número {numero}')
print(f'Unidade: {n[3]}')
print(f'Dezena: {n[2]}')
print(f'Centena: {n[1]}')
print(f'Milhar: {n[0]}')
